- name: This playbook will build the custom docker image which we will later use as a java application build machine
  hosts: localhost
  tasks:
    - name: Build alpine base docker custom image
      docker_image:
         docker_host: tcp://localhost:4243
         name: tektutor/devops-jenkins-slave:latest
         build:
           dockerfile: Dockerfile
           path: .
           pull: no
         state: present
         source: build
