- name: Configure nginx to a custom web root folder in CentOS 
  when: ( output.rc != 0 and ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf backup=yes
