- name: Configure web root folder in apache2
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify:
    - Restart apache2

- name: Grant permission to our custom document root folder
  copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf
  notify:
    - Restart apache2
